### ISSUE TITLE
Critical error on version 1.0.72

### ISSUE THREAD

**Issue by LuiggiTenorioK** [BSC-ES/autosubmit-config-parser#56]
While updating the Autosubmit API, I tried using the version 1.0.72 of the parser and it have a missing module that makes it unusable:

```
from autosubmitconfigparser.config.configcommon import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ltenorio/miniconda3/envs/py312/lib/python3.12/site-packages/autosubmitconfigparser/config/configcommon.py", line 39, in <module>
    from log.log import Log, AutosubmitCritical, AutosubmitError
ModuleNotFoundError: No module named 'log'
```

I highly suggest yanking that version on PyPI so users don't have to deal with this issue if they install this specific version.

@dbeltrankyl

**Comment by dbeltrankyl** [comment]
Hello @LuiggiTenorioK 

That's strange, that module is included  in this package

https://github.com/BSC-ES/autosubmit-config-parser/tree/main/log

```bash
(base) dbeltran@bsces107894:~$ python3 -m venv testasconfigparser72
(base) dbeltran@bsces107894:~$ source testasconfigparser72/bin/activate
(testASconfigparser72) (base) dbeltran@bsces107894:~$ pip freeze
autosubmitconfigparser==1.0.72
bscearth.utils==0.5.2
configobj==5.0.9
configparser==7.1.0
mock==5.1.0
pyparsing==3.2.0
python-dateutil==2.9.0.post0
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.12
six==1.17.0


(testASconfigparser72) (base) dbeltran@bsces107894:~$ pip install autosubmitconfigparser==1.0.72
```

```bash
(testASconfigparser72) (base) dbeltran@bsces107894:~$ python
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from autosubmitconfigparser.config.configcommon import *
```

And it is working for me

**Comment by LuiggiTenorioK** [comment]
I think that I know what is the issue now :smiling_face_with_tear: 

First I had `autosubmit` and `autosubmitconfigparser` installed but both packages have a dir `log/` in the root. That means that the `site-packages` will only have one `log` package from either one of the two packages. So, before running the import, I uninstalled `autosubmit` to just test the parser alone and this action deleted the `log`  package.

Sorry, it was a weird case but maybe we can move the `log/` dir inside `autosubmitconfigparser/` later. WDYT?

**Comment by dbeltrankyl** [comment]
Ah, interesting didn't know it could happen. 

In fact, both log folders are equivalent, ideally, the log should be excluded from Autosubmit and the Autosubmitconfigparser and be a different package. 

However, there are multiple issues with logging, and it is likely that we will change it or deprecate it in the future, so maybe we can discuss this in the dev meeting?

**Comment by LuiggiTenorioK** [comment]
Sure! I noticed that this is because of the `find_packages` function from `setuptools`. So, not only the `log` dir is downloaded, but also our tests directories :laughing: 

CC @kinow
